name: Feature Request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]

body:

- type: markdown
  attributes:
    value: |
      Thanks for suggesting a new feature.

- type: textarea
  attributes:
    label: What problem does this solve?

- type: textarea
  attributes:
    label: Describe the solution you would like

- type: textarea
  attributes:
    label: Additional context
